# Generated by Django 5.2.13 on 2026-04-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='category',
            field=models.CharField(choices=[('Link', 'Link (General)'), ('Email', 'Email Content'), ('Message', 'SMS/WhatsApp Message'), ('Other', 'Other/Unknown')], default='Link', max_length=20),
        ),
    ]
